version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./database/initDatabase.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/fillBase.sql:/docker-entrypoint-initdb.d/2.sql
      - ./database/fillRelations.sql:/docker-entrypoint-initdb.d/3.sql
    networks:
      tw_network:
        ipv4_address: 172.16.238.10
  # image-server:
  #   build: ./image-server
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $IMAGE_SERVER_LOCAL_PORT:$IMAGE_SERVER_DOCKER_PORT
  #   # volumes:
  #   #   - images:/home/Images
  #   stdin_open: true
  #   tty: true # "keep the container running" (https://kossy0701.medium.com/what-is-tty-true-in-docker-compose-yml-47a72891aee2)
  #   networks:
  #     tw_network:
  #       ipv4_address: 
  #         ipv4_address: 172.16.238.11
  website:
    depends_on:
      - mariadb
    build: ./website
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true # "keep the container running" (https://kossy0701.medium.com/what-is-tty-true-in-docker-compose-yml-47a72891aee2)
    networks:
      tw_network:
        ipv4_address: 172.16.238.12

volumes: 
  db:
  # images:
  
networks:
  tw_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24