
INSERT INTO TwinWorlds.CapsSpecies (NomSpecies,CapSpec) VALUES
	 ('Dragoïde','Armure Nat +1'),
	 ('Elfe','Yeux de Nacht'),
	 ('Félinidé','Yeux de Nacht'),
	 ('Gobelin','Yeux de Nacht'),
	 ('Honinrq','Armure Nat +1'),
	 ('Nain','Yeux de Nacht'),
	 ('Ocroch','Armure Nat +2'),
	 ('Rorag','Armure Nat +1'),
	 ('Rorel','Armure Nat +1'),
	 ('Rorel','Yeux de Nacht'),
	 ('Satyre','Herbivore'),
	 ('Satyre','Sabots');
INSERT INTO TwinWorlds.CompOrient (NomOrientation,NomComp,BonusO) VALUES
	 ('Alchimie','Alchimie',70),
	 ('Alchimie','Artisanat',65),
	 ('Alchimie','Botanique',65),
	 ('Apothicaire','Botanique',65),
	 ('Apothicaire','Connaissances',65),
	 ('Apothicaire','Pharmacologie',70),
	 ('Arts runiques','Connaissances',65),
	 ('Arts runiques','Linguistique',65),
	 ('Arts runiques','Runes',70),
	 ('Cavalerie','Constitution',15),
	 ('Cavalerie','Dressage',20),
	 ('Cavalerie','Equitation',30),
	 ('Cavalerie','Peur',15),
	 ('Cavalerie','Zoologie',60),
	 ('Cuisine','Botanique',65),
	 ('Cuisine','Cuisine',70),
	 ('Cuisine','Zoologie',65),
	 ('Dressage','Dressage',70),
	 ('Dressage','Traque',65),
	 ('Dressage','Zoologie',65),
	 ('Explorateur','Artisanat',75),
	 ('Explorateur','Botanique',25),
	 ('Explorateur','Cuisine',25),
	 ('Explorateur','Musique',25),
	 ('Explorateur','Pharmacologie',25),
	 ('Explorateur','Traque',25),
	 ('Ingénierie','Artisanat',65),
	 ('Ingénierie','Géologie',65),
	 ('Ingénierie','Ingénierie',70),
	 ('Médecine','Botanique',30),
	 ('Médecine','Connaissances',70),
	 ('Médecine','Medecine',70),
	 ('Médecine','Zoologie',30),
	 ('Musique','Linguistique',65),
	 ('Musique','Musique',70),
	 ('Musique','Psychologie',65),
	 ('Religion','Connaissances',65),
	 ('Religion','Linguistique',65),
	 ('Religion','Prière',70),
	 ('Vol','Discrétion',30),
	 ('Vol','Sabotage',70),
	 ('Vol','Vol',70);
INSERT INTO TwinWorlds.CompSpecies (NomSpecies,NomComp,BonusR) VALUES
	 ('Démonide','Constitution',15),
	 ('Démonide','Discrétion',-10),
	 ('Démonide','Linguistique',10),
	 ('Démonide','Peur',15),
	 ('Démonide','Sens Spirituel',20),
	 ('Démonide','Zoologie',5),
	 ('Diham','Agilité',-5),
	 ('Diham','Connaissances',15),
	 ('Diham','Constitution',20),
	 ('Diham','Force',-5),
	 ('Diham','Linguistique',5),
	 ('Diham','Nage',-10),
	 ('Diham','Peur',-10),
	 ('Diham','Prière',15),
	 ('Diham','Runes',10),
	 ('Diham','Social',15),
	 ('Diham','Vision',10),
	 ('Dragoïde','Connaissances',10),
	 ('Dragoïde','Cuisine',10),
	 ('Dragoïde','Discrétion',-10),
	 ('Dragoïde','Force',15),
	 ('Dragoïde','Medecine',10),
	 ('Dragoïde','Nage',-10),
	 ('Dragoïde','Peur',15),
	 ('Dragoïde','Sens Spirituel',10),
	 ('Dryade','Agilité',10),
	 ('Dryade','Alchimie',10),
	 ('Dryade','Botanique',20),
	 ('Dryade','Constitution',-10),
	 ('Dryade','Equitation',5),
	 ('Dryade','Force',-10),
	 ('Dryade','Géologie',15),
	 ('Dryade','Peur',-15),
	 ('Dryade','Pharmacologie',10),
	 ('Dryade','Social',30),
	 ('Elfe','Artisanat',10),
	 ('Elfe','Audition',15),
	 ('Elfe','Connaissances',10),
	 ('Elfe','Constitution',-10),
	 ('Elfe','Force',-10),
	 ('Elfe','Runes',10),
	 ('Elfe','Sens Spirituel',10),
	 ('Elfe','Social',5),
	 ('Elfe','Vision',10),
	 ('Félinidé','Agilité',10),
	 ('Félinidé','Audition',15),
	 ('Félinidé','Discrétion',20),
	 ('Félinidé','Equitation',-20),
	 ('Félinidé','Force',-10),
	 ('Félinidé','Nage',-15),
	 ('Félinidé','Peur',10),
	 ('Félinidé','Traque',15),
	 ('Félinidé','Vision',10),
	 ('Félinidé','Vol',5),
	 ('Glydas','Agilité',10),
	 ('Glydas','Alchimie',5),
	 ('Glydas','Constitution',-10),
	 ('Glydas','Discrétion',5),
	 ('Glydas','Force',-10),
	 ('Glydas','Nage',20),
	 ('Glydas','Prière',15),
	 ('Glydas','Psychologie',10),
	 ('Glydas','Sens Spirituel',15),
	 ('Gobelin','Agilité',15),
	 ('Gobelin','Alchimie',5),
	 ('Gobelin','Artisanat',15),
	 ('Gobelin','Constitution',-5),
	 ('Gobelin','Discrétion',20),
	 ('Gobelin','Force',-5),
	 ('Gobelin','Géologie',15),
	 ('Gobelin','Ingénierie',5),
	 ('Gobelin','Nage',-5),
	 ('Gobelin','Social',-10),
	 ('Honinrq','Agilité',-10),
	 ('Honinrq','Constitution',15),
	 ('Honinrq','Discrétion',-5),
	 ('Honinrq','Equitation',-5),
	 ('Honinrq','Force',25),
	 ('Honinrq','Peur',20),
	 ('Honinrq','Social',-10),
	 ('Humain','Artisanat',10),
	 ('Humain','Connaissances',5),
	 ('Humain','Linguistique',10),
	 ('Humain','Prière',10),
	 ('Humain','Social',20),
	 ('Lutin','Agilité',15),
	 ('Lutin','Alchimie',15),
	 ('Lutin','Artisanat',15),
	 ('Lutin','Botanique',15),
	 ('Lutin','Discrétion',25),
	 ('Lutin','Dressage',15),
	 ('Lutin','Equitation',-10),
	 ('Lutin','Force',-15),
	 ('Lutin','Nage',-10),
	 ('Lutin','Peur',-15),
	 ('Lutin','Social',10),
	 ('Lutin','Vol',15),
	 ('Naïade','Agilité',10),
	 ('Naïade','Alchimie',5),
	 ('Naïade','Constitution',-10),
	 ('Naïade','Equitation',-5),
	 ('Naïade','Force',-10),
	 ('Naïade','Nage',30),
	 ('Naïade','Peur',-15),
	 ('Naïade','Social',30),
	 ('Naïade','Zoologie',10),
	 ('Nain','Agilité',-10),
	 ('Nain','Artisanat',10),
	 ('Nain','Connaissances',10),
	 ('Nain','Constitution',15),
	 ('Nain','Equitation',-10),
	 ('Nain','Force',15),
	 ('Nain','Géologie',15),
	 ('Nain','Ingénierie',10),
	 ('Nain','Nage',-10),
	 ('Nain','Peur',-5),
	 ('Nain','Runes',5),
	 ('Nain','Social',10),
	 ('Ocroch','Agilité',-15),
	 ('Ocroch','Constitution',20),
	 ('Ocroch','Discrétion',-10),
	 ('Ocroch','Equitation',-5),
	 ('Ocroch','Force',20),
	 ('Ocroch','Géologie',15),
	 ('Ocroch','Peur',15),
	 ('Ocroch','Social',-10),
	 ('Ombou','Agilité',10),
	 ('Ombou','Audition',-10),
	 ('Ombou','Botanique',10),
	 ('Ombou','Constitution',10),
	 ('Ombou','Force',10),
	 ('Ombou','Nage',20),
	 ('Ombou','Peur',5),
	 ('Ombou','Pharmacologie',5),
	 ('Ombou','Sens Spirituel',10),
	 ('Ombou','Social',-10),
	 ('Ombou','Vision',-10),
	 ('Rorag','Agilité',-5),
	 ('Rorag','Audition',-5),
	 ('Rorag','Constitution',-15),
	 ('Rorag','Dressage',10),
	 ('Rorag','Equitation',30),
	 ('Rorag','Force',10),
	 ('Rorag','Nage',-5),
	 ('Rorag','Peur',10),
	 ('Rorag','Traque',5),
	 ('Rorag','Vision',-5),
	 ('Rorag','Zoologie',15),
	 ('Rorel','Artisanat',10),
	 ('Rorel','Audition',5),
	 ('Rorel','Connaissances',10),
	 ('Rorel','Constitution',-10),
	 ('Rorel','Discrétion',5),
	 ('Rorel','Equitation',10),
	 ('Rorel','Nage',-5),
	 ('Rorel','Runes',5),
	 ('Rorel','Vision',5),
	 ('Satyre','Botanique',15),
	 ('Satyre','Constitution',20),
	 ('Satyre','Discrétion',-15),
	 ('Satyre','Equitation',-10),
	 ('Satyre','Géologie',10),
	 ('Satyre','Nage',-15),
	 ('Satyre','Prière',10),
	 ('Satyre','Social',10),
	 ('Satyre','Traque',5),
	 ('Satyre','Zoologie',10);
INSERT INTO TwinWorlds.CompType (TypeBonus,NomComp,BonusT) VALUES
	 ('Apprentissage long','Connaissances',20),
	 ('Apprentissage long','Linguistique',10),
	 ('Arme','Agilité',10),
	 ('Arme','Force',10),
	 ('Arme','Peur',10),
	 ('Formation','Agilité',5),
	 ('Formation','Constitution',5),
	 ('Formation','Discrétion',5),
	 ('Formation','Force',5),
	 ('Formation','Nage',5),
	 ('Formation','Peur',5),
	 ('Maîtrise innée','Prière',20),
	 ('Maîtrise innée','Sens Spirituel',40),
	 ('Sensations spirituelles','Sens Spirituel',30);
INSERT INTO TwinWorlds.FacPosComp (NomFacPos,NomComp) VALUES
	 ('A prix coutant','Runes'),
	 ('Accumulation défensive','Constitution'),
	 ('Adaptation de l''artisan','Artisanat'),
	 ('Additions médicales','Pharmacologie'),
	 ('Agilité montée','Equitation'),
	 ('Aisance cristalline','Nage'),
	 ('Aisance marine','Nage'),
	 ('Alliages nouveaux','Ingénierie'),
	 ('Amplification de la potion','Alchimie'),
	 ('Analyse des vibrations','Géologie'),
	 ('Angle d''attaque','Connaissances'),
	 ('Anticipation','Psychologie'),
	 ('Anticipation du savoir','Connaissances'),
	 ('Apprentissage amélioré','Connaissances'),
	 ('Aura religieuse','Prière'),
	 ('Automatisation','Ingénierie'),
	 ('Autonomie spirituelle','Artisanat'),
	 ('Avantage du terrain','Géologie'),
	 ('Berceuse','Musique'),
	 ('Bruissement du Rift','Audition'),
	 ('Brutalité du muscle','Force'),
	 ('Calme pendant la tempête','Constitution'),
	 ('Capsule prête','Pharmacologie'),
	 ('Cavalerie','Equitation'),
	 ('Cavalier acrobate','Equitation'),
	 ('Chair de poule intimidante','Peur'),
	 ('Champ de vision élargi','Vision'),
	 ('Chant du mouvement','Musique'),
	 ('Choix entitaire','Prière'),
	 ('Classe naturelle','Linguistique'),
	 ('Cohésion générale','Discrétion'),
	 ('Compagnon vengé','Equitation'),
	 ('Compréhension mutuelle','Psychologie'),
	 ('Connaissance des plantes','Botanique'),
	 ('Connaissances des animaux','Zoologie'),
	 ('Contact des roches','Géologie'),
	 ('Cordage rapide','Agilité'),
	 ('Corps sur-entrainé','Constitution'),
	 ('Coup de fouet','Dressage'),
	 ('Courbure de la colonne','Agilité'),
	 ('Courbure du cristallin','Vision'),
	 ('Couverture des traces','Traque'),
	 ('Création armée','Artisanat'),
	 ('Cri de surprise','Discrétion'),
	 ('Cristallisation','Alchimie'),
	 ('Croche pieds','Sabotage'),
	 ('Culture du muscle','Force'),
	 ('Cynégétique totale','Traque'),
	 ('Danger de mort','Peur'),
	 ('Débattement','Nage'),
	 ('Déconcertation','Musique'),
	 ('Défense amplifiée','Force'),
	 ('Dépeçage efficace','Zoologie'),
	 ('Désarmement','Vol'),
	 ('Destrier de combat','Equitation'),
	 ('Détection personnelle','Sens Spirituel'),
	 ('Détective','Vision'),
	 ('Dialogue des yeux','Vision'),
	 ('Digestion persistente','Cuisine'),
	 ('Dissection','Botanique'),
	 ('Dissimulation découverte','Vol'),
	 ('Distanciation runique','Runes'),
	 ('Docteur Maboul','Medecine'),
	 ('Doigté','Medecine'),
	 ('Donner et recevoir','Social'),
	 ('Double optimisation','Artisanat'),
	 ('Drogue de vie','Pharmacologie'),
	 ('Durcissement de la peau','Pharmacologie'),
	 ('Echolocation','Audition'),
	 ('Efficience maximale','Discrétion'),
	 ('Emprisonnement','Sabotage'),
	 ('Entourage inspirant','Prière'),
	 ('Epice de la maison','Cuisine'),
	 ('Equipementier','Ingénierie'),
	 ('Erreur d''innattention','Discrétion'),
	 ('Erreur de dieu','Linguistique'),
	 ('Esclave','Peur'),
	 ('Esclave du cerveau','Medecine'),
	 ('Esprit de déduction','Psychologie'),
	 ('Estimation','Vol'),
	 ('Estimations justes','Connaissances'),
	 ('Estomac bien rempli','Cuisine'),
	 ('Etendue des sens','Sens Spirituel'),
	 ('Extraction spirituelle','Alchimie'),
	 ('Facilités de transformation','Sens Spirituel'),
	 ('Faune obéissante','Zoologie'),
	 ('Feuilles d''amour','Botanique'),
	 ('Filature interminable','Traque'),
	 ('Focus anatomique','Zoologie'),
	 ('Force d''impact','Force'),
	 ('Forgemagie','Ingénierie'),
	 ('Forts encouragements','Social'),
	 ('Fortune du saboteur','Sabotage'),
	 ('Fouille au corps','Vol'),
	 ('Foulée guidée','Discrétion'),
	 ('Gastronomie 5 étoiles','Cuisine'),
	 ('Gommages sablonneux','Géologie'),
	 ('Gymnastique','Agilité'),
	 ('Hébétude','Social'),
	 ('Herbivore','Botanique'),
	 ('Hors de contrôle','Prière'),
	 ('Hors de vue','Traque'),
	 ('Humainement stable','Peur'),
	 ('Hypersensibilité acoustique','Audition'),
	 ('Hypnose','Social'),
	 ('Immersion','Musique'),
	 ('Improvisation','Alchimie'),
	 ('In extremis','Psychologie'),
	 ('Incantation oubliée','Linguistique'),
	 ('Inception','Psychologie'),
	 ('Incision commune','Medecine'),
	 ('Influence des prières','Prière'),
	 ('Infra-audition','Audition'),
	 ('Inondation','Nage'),
	 ('Inspiration des gemmes','Géologie'),
	 ('Inspiration des légendes','Connaissances'),
	 ('Inspiration du vivant','Botanique'),
	 ('Instinct du Rift','Sens Spirituel'),
	 ('Intimidation alpha','Equitation'),
	 ('Intimidation constante','Peur'),
	 ('Jambes pliées','Vol'),
	 ('Langue des signes','Linguistique'),
	 ('Langues animales','Zoologie'),
	 ('Lien des runes','Runes'),
	 ('Lien spirituel','Ingénierie'),
	 ('Main invisible','Vol'),
	 ('Mains glissantes','Sabotage'),
	 ('Maîtrise des roches','Géologie'),
	 ('Maîtrise du végétal','Botanique'),
	 ('Maîtrise totale','Dressage'),
	 ('Maîtrise totale de l''alchimie','Alchimie'),
	 ('Matériaux rares','Artisanat'),
	 ('Médecine de guerre','Medecine'),
	 ('Médicament spirituel','Pharmacologie'),
	 ('Mental à toutes épreuves','Psychologie'),
	 ('Mimétisme','Linguistique'),
	 ('Moments partagés','Dressage'),
	 ('Multi-Exp','Dressage'),
	 ('Multitâche','Cuisine'),
	 ('Murmures du dresseur','Dressage'),
	 ('Muscle pur','Force'),
	 ('Musique magique','Musique'),
	 ('Nage tout-terrain','Nage'),
	 ('Nez fin','Traque'),
	 ('Ode aux héros','Musique'),
	 ('Odeur de la pluie','Traque'),
	 ('Omniscience','Connaissances'),
	 ('Ondes positives','Social'),
	 ('Onguent de contrôle','Alchimie'),
	 ('Oreille à réaction','Audition'),
	 ('Ouïe fine','Audition'),
	 ('Paillettes spirituelles','Cuisine'),
	 ('Parkour','Agilité'),
	 ('Pas de loup','Discrétion'),
	 ('Passion runes','Runes'),
	 ('Paume de l''intérieur','Force'),
	 ('Pèlerinage','Prière'),
	 ('Permanence de l''estomac','Cuisine'),
	 ('Peur prolongée','Peur'),
	 ('Pied léger','Discrétion'),
	 ('Piege invisible','Sabotage'),
	 ('Plan sans encombres','Ingénierie'),
	 ('Plantes à portée de main','Botanique'),
	 ('Pli du corps','Agilité'),
	 ('Poigne de fer','Force'),
	 ('Poing serré','Force'),
	 ('Point de pression','Medecine'),
	 ('Points mals protégés','Zoologie'),
	 ('Polyglotte','Linguistique'),
	 ('Posologie critique','Pharmacologie'),
	 ('Poussière de gemmes','Runes'),
	 ('Pouvoir des profondeurs','Nage'),
	 ('Précipité spirituel','Alchimie'),
	 ('Préparation minutieuse','Traque'),
	 ('Prise au vol','Agilité'),
	 ('Protection acoustique','Musique'),
	 ('Protection spirituelle','Sens Spirituel'),
	 ('Psychologie invasive','Psychologie'),
	 ('Psychologie inversée','Psychologie'),
	 ('Puissance de l''intimidation','Peur'),
	 ('Puissance de la faune','Zoologie'),
	 ('Puissance runique','Runes'),
	 ('Punition du blasphème','Prière'),
	 ('Rage','Dressage'),
	 ('Rayon spirituel','Sens Spirituel'),
	 ('Récompense de détection','Sens Spirituel'),
	 ('Réduction des marges','Sabotage'),
	 ('Réorganisation molléculaire','Ingénierie'),
	 ('Reprise en mains','Sabotage'),
	 ('Ressources rares','Ingénierie'),
	 ('Ricochet du métal','Géologie'),
	 ('Rodéo maîtrisé','Equitation'),
	 ('Rune de contrôle','Runes'),
	 ('Runes aux trésors','Runes'),
	 ('Sans peurs et sans reproches','Peur'),
	 ('Savoir instinctif','Connaissances'),
	 ('Science des accumulations','Connaissances'),
	 ('Second Souffle Véritable','Constitution'),
	 ('Seconde main','Vol'),
	 ('Sens des eaux profondes','Nage'),
	 ('Sens des langues','Linguistique'),
	 ('Sens du détail','Vision'),
	 ('Sens magique','Sens Spirituel'),
	 ('Sertissage','Artisanat'),
	 ('Sieste réparatrice','Cuisine'),
	 ('Simple prière','Prière'),
	 ('Socialement à l''aise','Social'),
	 ('Soin de l''âme','Pharmacologie'),
	 ('Solidité naturelle','Constitution'),
	 ('Sommeil de plomb','Constitution'),
	 ('Son du cerveau','Audition'),
	 ('Son du corps','Audition'),
	 ('Son inaudible','Musique'),
	 ('Souffle alchimique','Alchimie'),
	 ('Souffle de l''eau profonde','Nage'),
	 ('Souffle du juron','Linguistique'),
	 ('Souplesse','Agilité'),
	 ('Souplesse de rêve','Agilité'),
	 ('Soutien moral','Zoologie'),
	 ('Soutien social','Social'),
	 ('Stase des altérations','Botanique'),
	 ('Superagilité','Vol'),
	 ('Surprise latente','Discrétion'),
	 ('Survie','Constitution'),
	 ('Technique d''usure','Sabotage'),
	 ('Textiles de qualité','Artisanat'),
	 ('Traitement constant','Pharmacologie'),
	 ('Transhumanisme','Medecine'),
	 ('Transport équin','Equitation'),
	 ('Traque discrète','Traque'),
	 ('Union des bêtes','Dressage'),
	 ('Usure forcée','Géologie'),
	 ('Utilisation optimisée','Artisanat'),
	 ('Visée des artères','Medecine'),
	 ('Vision périphérique','Vision'),
	 ('Vitalité croissante','Constitution'),
	 ('Vivacité partagée','Dressage'),
	 ('Voir l''invisible','Vision'),
	 ('Voix enjôleuse','Social'),
	 ('Yeux à réaction','Vision');
INSERT INTO TwinWorlds.FacPosOrient (NomFacPos,NomOrientation) VALUES
	 ('4ème dimension','Spatiale'),
	 ('Acier trempé','Eau'),
	 ('Adaptation des milieux','Lumière'),
	 ('Altération de volonté','Illusions'),
	 ('Altérations organiques','Métamorphose'),
	 ('Amaterasu','Feu'),
	 ('Ami du froid','Glace'),
	 ('Anticoagulant','Sang'),
	 ('Armure spirituelle','Spirituelle'),
	 ('Art de la fusion','Invocation'),
	 ('Aura aqueuse','Eau'),
	 ('Aura cyclonique','Air'),
	 ('Aura de flammes','Feu'),
	 ('Aura de sang','Sang'),
	 ('Aura ferromagnétique','Métal'),
	 ('Aura froudroyante','Electricité'),
	 ('Aura glaciale','Glace'),
	 ('Aura multi-matérielle','Matérialisation'),
	 ('Aura tellurique','Terre'),
	 ('Aura volcanique','Lave'),
	 ('Autorité naturelle','Invocation'),
	 ('Bain de lave','Lave'),
	 ('Barrière de vent','Air'),
	 ('Barrière spirituelle personnelle','Explosive'),
	 ('Bénédiction de Capjut','Spatiale'),
	 ('Bis repetita','Temporelle'),
	 ('Blocus végétal','Végétale'),
	 ('Bombe sur pattes','Explosive'),
	 ('Bombification','Explosive'),
	 ('Bonheur du soin','Lumière'),
	 ('Bout portant destructeur','Explosive'),
	 ('Branchies spirituelles','Eau'),
	 ('Brisûre squelettique','Morts'),
	 ('Buche du réel','Bois'),
	 ('Bulle d''air','Air'),
	 ('Calque du Rift','Spectrale'),
	 ('Camouflage matériel','Matérialisation'),
	 ('Camouflage naturel parfait','Textiles'),
	 ('Canalisation de l''invocation','Invocation'),
	 ('Canalisation de la posture','Runique'),
	 ('Canalisation squelettique','Morts'),
	 ('Capture d''âme','Spirituelle'),
	 ('Carapace','Vermines'),
	 ('Carapace en liège renforcé','Bois'),
	 ('Casier dimensionnel','Spatiale'),
	 ('Casier spectral','Spectrale'),
	 ('Champ électromagnétique','Electricité'),
	 ('Changement de calque','Spectrale'),
	 ('Changement de place','Invocation'),
	 ('Charge spectrale','Spectrale'),
	 ('Coagulation forcée','Sang'),
	 ('Complétude insectoïde','Vermines'),
	 ('Contact du vivant','Bois'),
	 ('Contact interdimensionnel','Spatiale'),
	 ('Contact mortel','Afflictions'),
	 ('Contrôle des rêves','Illusions'),
	 ('Contrôle du terrain','Ombre'),
	 ('Contrôle parasitaire','Afflictions'),
	 ('Contrôle vestimentaire','Textiles'),
	 ('Copie parfaite','Métamorphose'),
	 ('Coque énergétique','Energie'),
	 ('Cordages d''autodéfense','Textiles'),
	 ('Corps particulier','Textiles'),
	 ('Corrosion','Vermines'),
	 ('Criticité de la vision','Oculaire'),
	 ('Dématérialisation','Matérialisation'),
	 ('Densité osseuse','Morts'),
	 ('Déplacement des runes','Runique'),
	 ('Destabilisation spectrale','Spectrale'),
	 ('Destruction d''armure','Explosive'),
	 ('Destruction par la lave','Lave'),
	 ('Déterioration de la santé','Afflictions'),
	 ('Dilatation du temps','Temporelle'),
	 ('Dimension spectrale','Spectrale'),
	 ('Dissociation du visible','Lumière'),
	 ('Division cellulaire','Cellulaire'),
	 ('Don d''es','Energie'),
	 ('Don de la nature','Végétale'),
	 ('Don de soi','Lien invocatoire'),
	 ('Double objet','Matérialisation'),
	 ('Douleur illusoire','Illusions'),
	 ('Duplication du mot','Mots'),
	 ('Ecailles de métal','Métal'),
	 ('Echange des corps','Morts'),
	 ('Encouragements profonds','Invocation'),
	 ('Espace fixe','Spatiale'),
	 ('Espace impossible','Spatiale'),
	 ('Etreinte de l''ombre','Ombre'),
	 ('Exception alliée','Métamorphose'),
	 ('Exception par consentement','Métamorphose'),
	 ('Exosquelette','Vermines'),
	 ('Explosivité du corps','Explosive'),
	 ('Extension de l''ombre','Ombre'),
	 ('Extension de la rune oculaire','Oculaire'),
	 ('Extension du territoire','Gravitation'),
	 ('Extra secondes','Temporelle'),
	 ('Fils d''énergie','Energie'),
	 ('Flux neuronal','Electricité'),
	 ('Force d''Hydris','Eau'),
	 ('Force dans le sang','Sang'),
	 ('Force de l''adversité','Explosive'),
	 ('Force du feu','Lave'),
	 ('Force du sous-sol','Terre'),
	 ('Forme aquatique','Eau'),
	 ('Forme d''ombre','Ombre'),
	 ('Forme de lave','Lave'),
	 ('Forme englaçonnée','Glace'),
	 ('Forme métallique','Métal'),
	 ('Forme minérale','Terre'),
	 ('Forme végétale','Végétale'),
	 ('Gain du lien','Lien invocatoire'),
	 ('Gemme du sacrifice','Spirituelle'),
	 ('Giga-Sangsue','Energie'),
	 ('Glace à température ambiante','Glace'),
	 ('Graines latentes','Végétale'),
	 ('Greffe permanente','Cellulaire'),
	 ('Guérison par le changement','Métamorphose'),
	 ('Haute-tension','Electricité'),
	 ('Illusions complètes','Illusions'),
	 ('Imitation forcée de l''ombre','Ombre'),
	 ('Immortalité','Temporelle'),
	 ('Immunité forte','Cellulaire'),
	 ('Immunité partagée','Cellulaire'),
	 ('Impact du terrain','Lumière'),
	 ('Instinct spatial','Spatiale'),
	 ('Intangibilité alliée','Spectrale'),
	 ('Inversion de position','Lien invocatoire'),
	 ('Inversion gravitationnelle','Gravitation'),
	 ('Invocation aqueuse majeure','Eau'),
	 ('Invocation aqueuse mineure','Eau'),
	 ('Invocation boisée majeure','Bois'),
	 ('Invocation boisée mineure','Bois'),
	 ('Invocation cellulaire majeure','Cellulaire'),
	 ('Invocation cellulaire mineure','Cellulaire'),
	 ('Invocation de foudre mineure','Electricité'),
	 ('Invocation élémentaire majeure','Feu'),
	 ('Invocation enflammée mineure','Feu'),
	 ('Invocation froudroyante majeure','Electricité'),
	 ('Invocation glaciale majeure','Glace'),
	 ('Invocation glaciale mineure','Glace'),
	 ('Invocation métallique majeure','Métal'),
	 ('Invocation métallique mineure','Métal'),
	 ('Invocation minérale majeure','Terre'),
	 ('Invocation minérale mineure','Terre'),
	 ('Invocation nuageuse majeure','Air'),
	 ('Invocation nuageuse mineure','Air'),
	 ('Invocation sanguine majeure','Sang'),
	 ('Invocation sanguine mineure','Sang'),
	 ('Invocation végétale majeure','Végétale'),
	 ('Invocation végétale mineure','Végétale'),
	 ('Invocation volcanique majeure','Lave'),
	 ('Invocation volcanique mineure','Lave'),
	 ('Izanami','Illusions'),
	 ('Lame sombre','Ombre'),
	 ('Langaraignée','Vermines'),
	 ('Langue de l''inconnu','Mots'),
	 ('Le Monde','Temporelle'),
	 ('Lien des morts','Morts'),
	 ('Lien gravitationnel','Gravitation'),
	 ('Lien runique','Runique'),
	 ('Linguistique spirituelle','Mots'),
	 ('Mains balladeuses','Spatiale'),
	 ('Maintien simplifié','Invocation'),
	 ('Maîtrise améliorée','Afflictions'),
	 ('Maîtrise des invocations','Invocation'),
	 ('Maîtrise du matériel','Matérialisation'),
	 ('Maladie auto-immune','Afflictions'),
	 ('Mange tout','Métal'),
	 ('Mega-Sangsue','Spirituelle'),
	 ('Métabolisme accéléré','Cellulaire'),
	 ('Miss météo','Air'),
	 ('Modulation ondulatoire','Lumière'),
	 ('Morsure de l''hiver','Glace'),
	 ('Mort des faibles','Afflictions'),
	 ('Naissance des astres','Gravitation'),
	 ('Nano-gravitation','Gravitation'),
	 ('Nuées','Vermines'),
	 ('Oeil de l''âme','Oculaire'),
	 ('Oeil de Méduse','Oculaire'),
	 ('Oeil spirituel de Nacht','Oculaire'),
	 ('Optimisation runique','Runique'),
	 ('Paralysie forte','Afflictions'),
	 ('Paratonnerre','Electricité'),
	 ('Partage de contact','Illusions'),
	 ('Peau brûlée','Feu'),
	 ('Pellicule de glace','Glace'),
	 ('Persistance spirituelle','Lien invocatoire'),
	 ('Photoguérison ','Lumière'),
	 ('Piqûre de l''élu','Vermines'),
	 ('Plante parlante','Végétale'),
	 ('Poigne de la fibre','Textiles'),
	 ('Portail de Pyros','Feu'),
	 ('Porte de l''eau','Eau'),
	 ('Portée runique','Runique'),
	 ('Premiers soins automatiques','Matérialisation'),
	 ('Présence des morts','Morts'),
	 ('Prestidigitation','Illusions'),
	 ('Prix du sang','Runique'),
	 ('Propulsion de feu','Feu'),
	 ('Propulsion explosive','Explosive'),
	 ('Puissance des liens du sang','Sang'),
	 ('Puissance des liens invocatoires','Lien invocatoire'),
	 ('Puissance des ténèbres','Ombre'),
	 ('Puissance sylvestre','Bois'),
	 ('Puissance volcanique pure','Lave'),
	 ('Puissances fusionnées','Lien invocatoire'),
	 ('Puissances simultannées','Lien invocatoire'),
	 ('Racines','Végétale'),
	 ('Recharge du mot','Mots'),
	 ('Recharge oculaire','Oculaire'),
	 ('Recharge spirituelle spéciale','Runique'),
	 ('Réécriture','Runique'),
	 ('Remerciement de Capjut','Morts'),
	 ('Remplacement invocatoire','Invocation'),
	 ('Renforcement','Cellulaire'),
	 ('Répulsion céleste','Gravitation'),
	 ('Sculpture boisée','Bois'),
	 ('Second lien','Lien invocatoire'),
	 ('Seconde chance','Temporelle'),
	 ('Seconde forme','Matérialisation'),
	 ('Seconde peau','Textiles'),
	 ('Seconde vie spirituelle','Spirituelle'),
	 ('Sens de la terre','Terre'),
	 ('Sens gravitationnel','Gravitation'),
	 ('Sensibilité accrue','Afflictions'),
	 ('Séparation des cellules','Métamorphose'),
	 ('Setae','Vermines'),
	 ('Sphère du temps vivant','Temporelle'),
	 ('Sphère sans mots','Mots'),
	 ('Stabilité métamorphique','Métamorphose'),
	 ('Superposition de propriétés','Textiles'),
	 ('Supplantation spirituelle','Morts'),
	 ('Suppléments','Spectrale'),
	 ('Surcharge','Energie'),
	 ('Surcouches','Métamorphose'),
	 ('Sursaut vital','Energie'),
	 ('Suvie sur le fil spirituel','Spirituelle'),
	 ('Télékinésie matérielle','Matérialisation'),
	 ('Télékinésie par interactions','Gravitation'),
	 ('Télépathie','Mots'),
	 ('Téléportation à l''ombre','Ombre'),
	 ('Téléportation par photons','Lumière'),
	 ('Temps des soins','Temporelle'),
	 ('Tir allié','Feu'),
	 ('Toucher de métal','Métal'),
	 ('Toucher de pierre','Terre'),
	 ('Transmutation métallique','Métal'),
	 ('Transmutation rocheuse','Terre'),
	 ('Transposition','Spirituelle'),
	 ('Tressage atomique','Textiles'),
	 ('Tribu sanguin','Oculaire'),
	 ('Ultramots','Mots'),
	 ('Unicité du réel ','Illusions'),
	 ('Vampirisation énergétique','Energie'),
	 ('Vampirisme','Sang'),
	 ('Vases communiquants','Energie'),
	 ('Vent permanent','Air'),
	 ('Vie sauvage','Bois'),
	 ('Vision totale','Oculaire'),
	 ('Vitesse de dieu','Electricité'),
	 ('Vitesse lumière','Lumière'),
	 ('Voeu de silence','Mots'),
	 ('Vol pur','Air'),
	 ('Zone de vol d''es','Spirituelle');
INSERT INTO TwinWorlds.FacPosSpecies (NomFacPos,NomSpecies) VALUES
	 ('Absorption gemmique','Nain'),
	 ('Action de la queue','Félinidé'),
	 ('Ailes de dragon','Dragoïde'),
	 ('Ailes du démon','Démonide'),
	 ('Alpha','Félinidé'),
	 ('Anti-pollution','Naïade'),
	 ('Arrangement du corps','Gobelin'),
	 ('Aspiration vitale','Ombou'),
	 ('Autotomie','Ombou'),
	 ('Bain royal','Ombou'),
	 ('Beauté sylvestre','Satyre'),
	 ('Blizzard','Glydas'),
	 ('Blocage par coup','Satyre'),
	 ('Bon apprenti','Elfe'),
	 ('Bonheur cumulé','Humain'),
	 ('Bouclier du corps','Rorel'),
	 ('Bouffée d''es','Dragoïde'),
	 ('Branchies naturelles','Ombou'),
	 ('Calcification du corps','Rorel'),
	 ('Casse acier','Honinrq'),
	 ('Chahut','Honinrq'),
	 ('Chance du lutin','Lutin'),
	 ('Charité bien ordonnée','Glydas'),
	 ('Coeur précieux','Nain'),
	 ('Compression des roches','Ocroch'),
	 ('Contact ancestral','Dryade'),
	 ('Contre-attaque partagée','Satyre'),
	 ('Corps spirituel','Elfe'),
	 ('Créature aquatique','Ombou'),
	 ('Crépuscule','Rorel'),
	 ('Croque-gemmes','Nain'),
	 ('Danse des rivières','Naïade'),
	 ('De la rivière à l''animal','Naïade'),
	 ('De végétal à animal','Dryade'),
	 ('Développement spirituel amélioré','Rorel'),
	 ('Dextérité gobeline','Gobelin'),
	 ('Dissociation du destin','Humain'),
	 ('Domination','Rorag'),
	 ('Duanties éveillées','Elfe'),
	 ('Durcissement naturel','Honinrq'),
	 ('Ecailles renforcées','Dragoïde'),
	 ('Echange de bons procédés','Glydas'),
	 ('Ecologisme','Dryade'),
	 ('Ecoute des animaux','Satyre'),
	 ('Energie de l''esprit','Elfe'),
	 ('Energie rapide','Lutin'),
	 ('Enfant de la nuit','Elfe'),
	 ('Epiderme spirituel','Rorag'),
	 ('Espièglerie','Lutin'),
	 ('Esprit clair','Elfe'),
	 ('Eveil forcé','Elfe'),
	 ('Exaltation','Gobelin'),
	 ('Fascination','Dryade'),
	 ('Férocité','Démonide'),
	 ('Forçat','Honinrq'),
	 ('Force latente','Honinrq'),
	 ('Force sylvaine','Dryade'),
	 ('Forme démoniaque complète','Démonide'),
	 ('Forme draconique complète','Dragoïde'),
	 ('Forme féline complète','Félinidé'),
	 ('Forme monstrueuse complète','Ombou'),
	 ('Forme ondine','Naïade'),
	 ('Forme parfaite','Humain'),
	 ('Forme sylvaine','Dryade'),
	 ('Gambrinus','Satyre'),
	 ('Grand explorateur','Diham'),
	 ('Griffes renforcées','Félinidé'),
	 ('Hiver agréable','Glydas'),
	 ('Inévitable','Satyre'),
	 ('Inflexion du malheur','Démonide'),
	 ('Initial','Gobelin'),
	 ('Inspiration nouvelle','Humain'),
	 ('Instinct maternel','Humain'),
	 ('Instinct protecteur','Satyre'),
	 ('Intensité maximale','Diham'),
	 ('Intimidation démoniaque naturelle','Démonide'),
	 ('Intrusion en combat','Lutin'),
	 ('Lacérations','Rorag'),
	 ('Lien équin','Rorag'),
	 ('Main des ténèbres','Gobelin'),
	 ('Maîtrise passive de la coagulation','Démonide'),
	 ('Maîtrise sur le destin','Diham'),
	 ('Malice de l''eau','Ombou'),
	 ('Marche funèbre','Humain'),
	 ('Miroir d''eau','Naïade'),
	 ('Modèle intouchable','Dryade'),
	 ('Modulation spirituelle','Rorel'),
	 ('Mouvement des plaques','Ocroch'),
	 ('Mouvement subtil','Félinidé'),
	 ('Nain du sous-sol','Nain'),
	 ('Nerfs à vif','Honinrq'),
	 ('Nyctalope','Félinidé'),
	 ('Oeil de lynx','Félinidé'),
	 ('Omnipotence aquatique','Naïade'),
	 ('Origines draconiques','Dragoïde'),
	 ('Origines monstrueuses','Gobelin'),
	 ('Paume portante','Rorel'),
	 ('Peau de pierre','Nain'),
	 ('Phénix','Diham'),
	 ('Pieds vifs','Lutin'),
	 ('Polissage','Ocroch'),
	 ('Polydactyle','Lutin'),
	 ('Pont des deux mondes','Diham'),
	 ('Port de roche','Ocroch'),
	 ('Positionnement des sabots','Satyre'),
	 ('Potentiel sanguin','Rorag'),
	 ('Prise de confiance','Humain'),
	 ('Prise de roc','Nain'),
	 ('Protection complète','Rorel'),
	 ('Puissance de la mort','Démonide'),
	 ('Puissance du rocher','Nain'),
	 ('Puissance ondine','Naïade'),
	 ('Raffermissement','Rorel'),
	 ('Réactions extrêmes','Diham'),
	 ('Réception du soin','Glydas'),
	 ('Regénération superficielle','Honinrq'),
	 ('Réorientation','Ocroch'),
	 ('Robustesse','Rorag'),
	 ('Ruine du corps','Ocroch'),
	 ('Sang chaud','Dragoïde'),
	 ('Sang démoniaque','Démonide'),
	 ('Sang froid','Glydas'),
	 ('Saumure','Ombou'),
	 ('Sauna','Dragoïde'),
	 ('Saut félin','Félinidé'),
	 ('Sensibilité des cristaux','Nain'),
	 ('Souffle légendaire','Humain'),
	 ('Spiritualisation du matériel','Diham'),
	 ('Supériorité','Lutin'),
	 ('Surprise de petite taille','Gobelin'),
	 ('Tambour rocailleux','Ocroch'),
	 ('Tête dure','Honinrq'),
	 ('Torrent de sang','Rorag'),
	 ('Touches sournoises','Gobelin'),
	 ('Tripe Souffle','Lutin'),
	 ('Ultime instant','Glydas'),
	 ('Union du milieu','Ocroch'),
	 ('Vendetta alliée','Dragoïde'),
	 ('Vigueur du sang','Rorag'),
	 ('Voile blanc','Diham'),
	 ('Voix de la forêt','Dryade'),
	 ('Voix du coquillage','Naïade'),
	 ('Yeux d''elfe','Elfe'),
	 ('Zéro absolu','Glydas');
INSERT INTO TwinWorlds.FacPosStyleCombat (NomFacPos,NomStyle) VALUES
	 ('Ajustement','Arme de tir/lancer'),
	 ('Anti-contre','Arme à une main'),
	 ('Attaque majoritaire','Arme à une main'),
	 ('Bourreau','Arme à deux mains'),
	 ('Brise armure','Arme à deux mains'),
	 ('Changement de rythme','Arme de type poing/pied/dague'),
	 ('Contre critique','Arme à une main'),
	 ('Contre fort','Arme à une main'),
	 ('Contre nature','Protection (Toutes armes)'),
	 ('Corne du combat','Protection (Toutes armes)'),
	 ('Corps entrainé','Protection (Toutes armes)'),
	 ('Coup de bouclier puissant','Arme à une main'),
	 ('Couverture','Arme de tir/lancer'),
	 ('Destabilisation','Arme de type poing/pied/dague'),
	 ('Double usure','Arme à deux mains'),
	 ('Etourdissement','Arme de type poing/pied/dague'),
	 ('Execution instantannée','Arme de type poing/pied/dague'),
	 ('Force de l''esprit','Protection (Toutes armes)'),
	 ('Force du nombre','Arme à une main'),
	 ('Hégémonie du berserker','Arme à deux mains'),
	 ('Insaisissable','Arme de type poing/pied/dague'),
	 ('Joie du sang','Arme à deux mains'),
	 ('Multi-attaques','Arme à une main'),
	 ('Multiplication des forces','Protection (Toutes armes)'),
	 ('Musculation forcée','Arme de type poing/pied/dague'),
	 ('Patience','Arme à deux mains'),
	 ('Percée','Arme de tir/lancer'),
	 ('Polyvalence armée','Protection (Toutes armes)'),
	 ('Prise d''opportunités','Arme de type poing/pied/dague'),
	 ('Puissance du berserker','Arme à deux mains'),
	 ('Régularité dans la difficulté','Arme de tir/lancer'),
	 ('Ricochet','Arme de tir/lancer'),
	 ('Souffle du berserker','Arme à deux mains'),
	 ('Sur le fil de l''arc','Arme de tir/lancer'),
	 ('Surprise désagréable','Arme de type poing/pied/dague'),
	 ('Tir précis','Arme de tir/lancer'),
	 ('Ultra défense','Protection (Toutes armes)'),
	 ('Visée simultanée','Arme de tir/lancer'),
	 ('Vision de l''esprit','Protection (Toutes armes)'),
	 ('Vivacité','Arme à une main');
INSERT INTO TwinWorlds.MagiesFusionnees (NomMagieFusionnee,NomMagie,NomMagieBis) VALUES
	 ('Lave','Feu','Terre'),
	 ('Spectrale','Matérialisation','Spatiale');
INSERT INTO TwinWorlds.MagiesPartielles (NomMagiePartielle,NomMagie) VALUES
	 ('Afflictions','Cellulaire'),
	 ('Bois','Végétale'),
	 ('Explosive','Feu'),
	 ('Glace','Eau'),
	 ('Gravitation','Spatiale'),
	 ('Lien invocatoire','Invocation'),
	 ('Lumière','Illusions'),
	 ('Métamorphose','Cellulaire'),
	 ('Mots','Runique'),
	 ('Ombre','Illusions'),
	 ('Sang','Eau');